name: Display a GitHub Environment Variable
on: [workflow_dispatch]
jobs:
  display:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: Display Method 1
        run: echo $GITHUB_REPOSITORY
      - name: Display Method 2
        run: echo ${{ env.GITHUB_REPOSITORY }}
      - name: Display Method 3
        run: echo ${{ github.env.GITHUB_REPOSITORY }}
      - name: Display Method 4
        run: echo ${{ github.repository }}
