name: Hello-World
on: [push, workflow_dispatch]
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello World
        run: echo Hello, world!
      - name: Print environment varariables
        run: env | grep GITHUB
